// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cijfeqwwsslitdvnpmnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpamZlcXd3c3NsaXRkdm5wbW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjM3NzIsImV4cCI6MjA2NTQ5OTc3Mn0.gE6aAGJLML7rNG2F_LCplWIninVose36xtBODC0iM7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);